// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  //Web//
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbiMP80EmE0x2nzyVM_S2rQII8mTpcksk',
    appId: '1:333867839787:web:b05ade8872f276a569d56e',
    messagingSenderId: '333867839787',
    projectId: 'smartdrip-6b1b4',
    authDomain: 'smartdrip-6b1b4.firebaseapp.com',

    databaseURL:
        'https://smartdrip-6b1b4-default-rtdb.firebaseio.com',

    storageBucket: 'smartdrip-6b1b4.firebasestorage.app',
    measurementId: 'G-P7KWSWLT9D',
  );

  //Android//
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJvNqQBvbdyWIIp7BN7wwm2NDLnhc6NLQ',
    appId: '1:333867839787:android:ce250bc4221d35f469d56e',
    messagingSenderId: '333867839787',
    projectId: 'smartdrip-6b1b4',

    
    databaseURL:
        'https://smartdrip-6b1b4-default-rtdb.firebaseio.com',

    storageBucket: 'smartdrip-6b1b4.firebasestorage.app',
  );

 //iOS//
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFBO8e-Mc7EU31pXTy83b2tdKTzrZvkpo',
    appId: '1:333867839787:ios:2881c143ca181e0169d56e',
    messagingSenderId: '333867839787',
    projectId: 'smartdrip-6b1b4',

    
    databaseURL:
        'https://smartdrip-6b1b4-default-rtdb.firebaseio.com',

    storageBucket: 'smartdrip-6b1b4.firebasestorage.app',
    iosBundleId: 'com.example.smartDrip',
  );

  //Windows//
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbiMP80EmE0x2nzyVM_S2rQII8mTpcksk',
    appId: '1:333867839787:web:fe9ca466929e4ff069d56e',
    messagingSenderId: '333867839787',
    projectId: 'smartdrip-6b1b4',
    authDomain: 'smartdrip-6b1b4.firebaseapp.com',

 
    databaseURL:
        'https://smartdrip-6b1b4-default-rtdb.firebaseio.com',

    storageBucket: 'smartdrip-6b1b4.firebasestorage.app',
    measurementId: 'G-NKVHL8SNTL',
  );

   //MacOS//
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFBO8e-Mc7EU31pXTy83b2tdKTzrZvkpo',
    appId: '1:333867839787:ios:2881c143ca181e0169d56e',
    messagingSenderId: '333867839787',
    projectId: 'smartdrip-6b1b4',

    databaseURL:
        'https://smartdrip-6b1b4-default-rtdb.firebaseio.com',

    storageBucket: 'smartdrip-6b1b4.firebasestorage.app',
    iosBundleId: 'com.example.smartDrip',
  );
}